# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()

nd1=np.array([1,2,3])
# Create a 2-dimensional NumPy array using np.array()
nd2=np.array([[1,2,3],[4,5,6]])
nd2.shape
# Create a 3-dimensional Numpy array using np.array()
nd3=np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])
nd3.shape

(2, 3, 3)

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [6]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
nd1.size,nd1.shape,nd1.dtype,nd1.ndim,type(nd1)

(3, (3,), dtype('int32'), 1, numpy.ndarray)

In [7]:
# Attributes of 2-dimensional array
nd2.size,nd2.shape,nd2.dtype,nd2.ndim,type(nd2)

(6, (2, 3), dtype('int32'), 2, numpy.ndarray)

In [8]:
# Attributes of 3-dimensional array
nd3.size,nd3.shape,nd3.dtype,nd3.ndim,type(nd3)

(18, (2, 3, 3), dtype('int32'), 3, numpy.ndarray)

In [17]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(np.random.randint(10, size=(5, 3)), 
                                    columns=['a', 'b', 'c'])
df

a  b  c
0  0  9  9
1  7  9  6
2  2  7  7
3  4  9  5
4  8  1  1

In [18]:
# Create an array of shape (10, 2) with only ones
ones=np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
ones.astype(int)


array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [20]:
# Create an array of shape (7, 2, 3) of only zeros
zeros=np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [22]:
# Create an array within a range of 0 and 100 with step 3
ar=np.arange(0,100,2)
ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [23]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a2=np.random.randint(10,size=(7,2))
a2

array([[4, 3],
       [2, 9],
       [3, 0],
       [9, 3],
       [5, 7],
       [6, 0],
       [0, 8]])

In [26]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
af=np.random.random((3,5))
af

array([[0.88657346, 0.86553731, 0.72571788, 0.00866808, 0.04975149],
       [0.15883095, 0.89889125, 0.72243901, 0.37990604, 0.19710246],
       [0.68432602, 0.16384487, 0.09469368, 0.67606855, 0.31418308]])

In [28]:
# Set the random seed to 42
np.random.seed(seed=24)

# Create a random array of numbers between 0 & 10 of size (4, 6)
ac=np.random.randint(10,size=(4,6))
ac

array([[2, 3, 0, 7, 1, 1],
       [1, 4, 4, 3, 2, 3],
       [3, 7, 9, 2, 7, 7],
       [9, 3, 0, 1, 1, 7]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [39]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
ax=np.random.randint(10,size=(3,7))
 
# Find the unique numbers in the array you just created
ax

array([[4, 4, 2, 1, 6, 9, 8],
       [6, 1, 2, 4, 3, 8, 5],
       [1, 1, 4, 2, 0, 4, 3]])

In [41]:
# Find the 0'th index of the latest array you created
ax[0]
ax.shape

(3, 7)

In [40]:
# Get the first 2 rows of latest array you created
ax[:2]

array([[4, 4, 2, 1, 6, 9, 8],
       [6, 1, 2, 4, 3, 8, 5]])

In [42]:
# Get the first 2 rows of latest array you created
ax[:2]

array([[4, 4, 2, 1, 6, 9, 8],
       [6, 1, 2, 4, 3, 8, 5]])

In [43]:
# Get the first 2 values of the first 2 rows of the latest array
ax[:2,:2]

array([[4, 4],
       [6, 1]])

In [47]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
ones=np.ones((3,5))
rd=np.random.randint(10,size=(3,5))
ones,rd

(array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[8, 6, 2, 6, 0],
        [1, 1, 8, 3, 5],
        [5, 0, 6, 2, 5]]))

In [48]:
# Add the two arrays together
ones+rd

array([[9., 7., 3., 7., 1.],
       [2., 2., 9., 4., 6.],
       [6., 1., 7., 3., 6.]])

In [49]:
# Create another array of ones of shape (5, 3)
one2=np.ones((5,3))
one2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [53]:
# Try add the array of ones and the other most recent array together
ones+one2.reshape(3,5)

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [55]:
# Create another array of ones of shape (3, 5)
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 5))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
x2

array([[3, 7, 9, 7, 1],
       [8, 5, 5, 5, 9],
       [9, 5, 1, 2, 6]])

In [57]:
# Subtract the new array of ones from the other most recent array
ones-x2

array([[-2., -6., -8., -6.,  0.],
       [-7., -4., -4., -4., -8.],
       [-8., -4.,  0., -1., -5.]])

In [58]:
# Multiply the ones array with the latest array
ones * x2

array([[3., 7., 9., 7., 1.],
       [8., 5., 5., 5., 9.],
       [9., 5., 1., 2., 6.]])

In [59]:
# Take the latest array to the power of 2 using '**'
x2 ** 2

array([[ 9, 49, 81, 49,  1],
       [64, 25, 25, 25, 81],
       [81, 25,  1,  4, 36]], dtype=int32)

In [60]:
# Do the same thing with np.square()
np.square(x2)

array([[ 9, 49, 81, 49,  1],
       [64, 25, 25, 25, 81],
       [81, 25,  1,  4, 36]], dtype=int32)

In [61]:
# Find the mean of the latest array using np.mean()
np.mean(x2)

5.466666666666667

In [62]:
# Find the maximum of the latest array using np.max()
np.max(x2)

9

In [63]:
# Find the minimum of the latest array using np.min()
np.min(x2)

1

In [64]:
# Find the standard deviation of the latest array
np.std(x2)

2.679966832298904

In [65]:
# Find the variance of the latest array
np.var(x2)

7.182222222222222

In [31]:
# Reshape the latest array to (3, 5, 1)


In [66]:
# Transpose the latest array
x2.reshape(3,5,1)

array([[[3],
        [7],
        [9],
        [7],
        [1]],

       [[8],
        [5],
        [5],
        [5],
        [9]],

       [[9],
        [5],
        [1],
        [2],
        [6]]])

What does the transpose do?

In [67]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
 
x4 = np.random.randint(10, size=(3, 2))  # Two-dimensional array
x5 = np.random.randint(10, size=(3, 2))  # Three-dimensional array
x4,x5

(array([[4, 4],
        [5, 0],
        [1, 3]]),
 array([[3, 0],
        [0, 1],
        [2, 0]]))

In [69]:
# Perform a dot product on the two newest arrays you created
np.dot(x4,x5.T)

array([[12,  4,  8],
       [15,  0, 10],
       [ 3,  3,  2]])

In [76]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)

x6 = np.random.randint(10, size=(4, 3))  # Two-dimensional array
x7 = np.random.randint(10, size=(4, 3))  # Three-dimensional array
x6,x7
x6.shape,x7.shape

((4, 3), (4, 3))

In [80]:
# Perform a dot product on the two newest arrays you created
np.dot(x6.T,x7)

array([[ 60,  33,  63],
       [ 34,  46,  53],
       [111,  70,  81]])

It doesn't work. How would you fix it?

In [81]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
x6.T

array([[0, 7, 0, 2],
       [0, 2, 2, 5],
       [3, 8, 5, 0]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [82]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables

x8 = np.random.randint(10, size=(4, 2))  # Two-dimensional array
x9 = np.random.randint(10, size=(4, 2))  # Three-dimensional array
x8,x9

(array([[4, 0],
        [8, 7],
        [5, 7],
        [6, 7]]),
 array([[9, 2],
        [9, 2],
        [0, 2],
        [6, 1]]))

In [83]:
# Compare the two arrays with '>'
x8>x9

array([[False, False],
       [False,  True],
       [ True,  True],
       [False,  True]])

What happens when you compare the arrays with `>`?

In [84]:
# Compare the two arrays with '>='
x8 >= x9

array([[False, False],
       [False,  True],
       [ True,  True],
       [ True,  True]])

In [86]:
# Find which elements of the first array are greater than 7
x8>7

array([[False, False],
       [ True, False],
       [False, False],
       [False, False]])

In [87]:
# Which parts of each array are equal? (try using '==')
x8==x9

array([[False, False],
       [False, False],
       [False, False],
       [ True, False]])

In [88]:
# Sort one of the arrays you just created in ascending order
np.sort(x8)

array([[0, 4],
       [7, 8],
       [5, 7],
       [6, 7]])

In [89]:
# Sort the indexes of one of the arrays you just created
np.argsort(x8)

array([[1, 0],
       [1, 0],
       [0, 1],
       [0, 1]], dtype=int64)

In [90]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(x8)

2

In [91]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(x9)

4

In [93]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(x9,axis=1)

array([0, 0, 1, 0], dtype=int64)

In [94]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(x8,axis=0)

array([0, 0], dtype=int64)

In [96]:
# Create an array of normally distributed random numbers
np.random.randn(3,5)

array([[-0.23846001, -0.25755287, -0.13005679,  0.17032683, -1.20505925],
       [-0.11468008, -0.52932392, -1.11298149, -0.25946234, -0.99222866],
       [-0.46110384,  0.73076017,  1.64748972, -0.55613285, -1.29985501]])

In [97]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [106]:
z=np.arange(15).reshape(3,5)
z,z.shape,z.ndim,z.dtype,z.size,z.itemsize

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 (3, 5),
 2,
 dtype('int32'),
 15,
 4)

In [108]:
b = np.array([(1.5,2,3), (4,5,6)])
b,b.shape

(array([[1.5, 2. , 3. ],
        [4. , 5. , 6. ]]),
 (2, 3))

In [113]:
np.arange(10,30,5),np.arange(0,2,0.3)

(array([10, 15, 20, 25]), array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8]))

In [115]:
np.linspace(0,2,9) # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [118]:
x = np.linspace( 0, 2*3.14, 100 )        # useful to evaluate function at lots of points
f=np.sin(x)


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.